name: Coldcard firmware (4.1.3)

on:
  workflow_dispatch

jobs:
  call-coldcard-fw-workflow:
    uses: ./.github/workflows/coldcard-fw-workflow.yml
    with:
      tag: 2021-09-02T1752-v4.1.3
      version: 4.1.3
